apiVersion: v1
kind: ServiceAccount
metadata:
  name: trader-provisioner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trader-provisioner
subjects:
  - kind: ServiceAccount
    name: trader-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io